package com.karursdo.report

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.util.Locale

/** One date-wise line in a Mail Overseer programme report. */
data class MoReportRow(val date: LocalDate, val details: String, val author: String?)

/**
 * Renders a professional, letterhead-style PDF of a Mail Overseer's date-wise tour programme for a
 * chosen period, and opens/shares it. Drawn directly with [PdfDocument] so the result is a real file
 * (no print dialog) that reads identically on every device. Body text is Palatino Linotype 12pt with
 * a fully ruled, aligned table.
 */
object MoReportPdf {

    // A4 @ 72dpi.
    private const val PAGE_W = 595
    private const val PAGE_H = 842
    private const val MARGIN = 40f

    // Brand palette (matches the app's report letterhead navy).
    private const val NAVY = 0xFF16315C.toInt()
    private const val NAVY_DEEP = 0xFF1F3864.toInt()
    private const val INK = 0xFF0F172A.toInt()
    private const val MUTED = 0xFF5B6472.toInt()
    private const val LINE = 0xFFCBD5E1.toInt()
    private const val ROW_ALT = 0xFFF3F6FB.toInt()
    private const val ACCENT = 0xFF0E7490.toInt()

    private val DATE_FULL = DateTimeFormatter.ofPattern("dd MMM yyyy", Locale.ENGLISH)
    private val DAY_FMT = DateTimeFormatter.ofPattern("EEEE", Locale.ENGLISH)
    private val STAMP = DateTimeFormatter.ofPattern("dd MMM yyyy, h:mm a", Locale.ENGLISH)

    // Table geometry.
    private const val DATE_W = 120f
    private const val AUTHOR_W = 105f
    private const val CELL_PAD = 9f
    private const val V_PAD = 9f
    private const val BODY_SIZE = 12f
    private const val LINE_H = 16.5f

    fun generate(
        context: Context,
        beatTitle: String,
        moName: String?,
        from: LocalDate,
        to: LocalDate,
        rows: List<MoReportRow>
    ): File {
        val serif = loadFont(context, "fonts/pala.ttf") ?: Typeface.SERIF
        val serifBold = loadFont(context, "fonts/palab.ttf")
            ?: Typeface.create(Typeface.SERIF, Typeface.BOLD)

        val doc = PdfDocument()

        val titlePaint = paint(Color.WHITE, 20f, serifBold)
        val subPaint = paint(0xFFDCE4F5.toInt(), 11f, serif)
        val kicker = paint(0xFFB9CBEC.toInt(), 8.5f, serifBold).apply { letterSpacing = 0.14f }
        val metaLabel = paint(MUTED, 8.5f, serifBold).apply { letterSpacing = 0.08f }
        val metaValue = paint(INK, 12f, serifBold)
        val metaAccent = paint(ACCENT, 12f, serifBold)
        val thHead = paint(Color.WHITE, 11f, serifBold).apply { letterSpacing = 0.05f }
        val tdDate = paint(INK, BODY_SIZE, serifBold)
        val tdDay = paint(ACCENT, 10f, serif)
        val tdBody = paint(INK, BODY_SIZE, serif)
        val tdAuthor = paint(MUTED, 11f, serif)
        val footPaint = paint(MUTED, 9f, serif)
        val emptyPaint = paint(MUTED, 13f, serif)

        val right = PAGE_W - MARGIN
        // Column x-boundaries: date | programme | by
        val x0 = MARGIN
        val x1 = MARGIN + DATE_W
        val x2 = right - AUTHOR_W
        val x3 = right
        val progW = x2 - x1

        val ascent = -tdBody.fontMetrics.ascent

        var pageNo = 0
        var page: PdfDocument.Page? = null
        var canvas: Canvas? = null
        var y = 0f

        fun footer(c: Canvas) {
            c.drawLine(MARGIN, PAGE_H - 34f, right, PAGE_H - 34f, stroke(LINE, 0.8f))
            c.drawText("Generated by the Karur SDO app · $beatTitle", MARGIN, PAGE_H - 20f, footPaint)
            val pg = "Page $pageNo"
            c.drawText(pg, right - footPaint.measureText(pg), PAGE_H - 20f, footPaint)
        }

        fun header(c: Canvas) {
            val bandH = 94f
            c.drawRect(0f, 0f, PAGE_W.toFloat(), bandH, fill(NAVY))
            c.drawRect(0f, bandH, PAGE_W.toFloat(), bandH + 4f, fill(ACCENT))
            val tx = MARGIN
            c.drawText("DEPARTMENT OF POSTS  ·  KARUR SUB DIVISION", tx, 33f, kicker)
            c.drawText("Mail Overseer — Tour Programme", tx, 60f, titlePaint)
            c.drawText(beatTitle + (moName?.let { "  ·  $it" } ?: ""), tx, 79f, subPaint)
        }

        fun tableHeader(c: Canvas, top: Float): Float {
            val h = 27f
            c.drawRect(x0, top, x3, top + h, fill(NAVY_DEEP))
            val by = top + h / 2f + (-thHead.fontMetrics.ascent - thHead.fontMetrics.descent) / 2f
            c.drawText("DATE", x0 + CELL_PAD, by, thHead)
            c.drawText("PROGRAMME", x1 + CELL_PAD, by, thHead)
            c.drawText("ENTERED BY", x2 + CELL_PAD, by, thHead)
            // Column dividers within the header.
            c.drawLine(x1, top, x1, top + h, stroke(0x40FFFFFF, 0.8f))
            c.drawLine(x2, top, x2, top + h, stroke(0x40FFFFFF, 0.8f))
            return top + h
        }

        fun meta(c: Canvas) {
            val top = 116f
            c.drawText("PERIOD", MARGIN, top, metaLabel)
            c.drawText("${from.format(DATE_FULL)}   –   ${to.format(DATE_FULL)}", MARGIN, top + 16f, metaValue)

            c.drawText("GENERATED", right - 210f, top, metaLabel)
            c.drawText(STAMP.format(LocalDateTime.now()), right - 210f, top + 16f, metaValue)

            val entries = "${rows.size} entr${if (rows.size == 1) "y" else "ies"}"
            c.drawText(entries, right - metaAccent.measureText(entries), top + 16f, metaAccent)
        }

        fun newPage(withMeta: Boolean) {
            pageNo++
            val p = doc.startPage(PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, pageNo).create())
            page = p
            val c = p.canvas
            canvas = c
            header(c)
            var top = 134f
            if (withMeta) { meta(c); top = 150f }
            y = tableHeader(c, top)
        }

        fun ensure(space: Float) {
            if (canvas == null) { newPage(true); return }
            if (y + space > PAGE_H - 48f) {
                footer(canvas!!)
                doc.finishPage(page!!)
                newPage(false)
            }
        }

        if (rows.isEmpty()) {
            ensure(0f)
            val c = canvas!!
            val msg = "No programme entries for this period."
            c.drawText(msg, (PAGE_W - emptyPaint.measureText(msg)) / 2f, y + 60f, emptyPaint)
        } else {
            rows.forEachIndexed { idx, r ->
                val bodyLines = r.details.split("\n").flatMap { wrap(it, tdBody, progW - 2 * CELL_PAD) }
                val rowH = maxOf(42f, bodyLines.size * LINE_H + 2 * V_PAD)
                ensure(rowH)
                val c = canvas!!

                if (idx % 2 == 1) c.drawRect(x0, y, x3, y + rowH, fill(ROW_ALT))

                val topBaseline = y + V_PAD + ascent
                // Date + weekday (top-aligned to the first programme line).
                c.drawText(r.date.format(DATE_FULL), x0 + CELL_PAD, topBaseline, tdDate)
                c.drawText(r.date.format(DAY_FMT), x0 + CELL_PAD, topBaseline + 15f, tdDay)

                // Programme (wrapped).
                var by = topBaseline
                for (ln in bodyLines) { c.drawText(ln, x1 + CELL_PAD, by, tdBody); by += LINE_H }

                // Entered by.
                r.author?.let {
                    c.drawText(ellipsize(it, tdAuthor, AUTHOR_W - 2 * CELL_PAD), x2 + CELL_PAD, topBaseline, tdAuthor)
                }

                // Ruled grid: outer + column verticals and the bottom border.
                c.drawLine(x0, y, x0, y + rowH, stroke(LINE, 0.7f))
                c.drawLine(x1, y, x1, y + rowH, stroke(LINE, 0.7f))
                c.drawLine(x2, y, x2, y + rowH, stroke(LINE, 0.7f))
                c.drawLine(x3, y, x3, y + rowH, stroke(LINE, 0.7f))
                c.drawLine(x0, y + rowH, x3, y + rowH, stroke(LINE, 0.7f))
                y += rowH
            }
            // Left & right outer borders for the last page's table are covered by dividers at x0/x3:
        }

        canvas?.let { footer(it) }
        page?.let { doc.finishPage(it) }

        val dir = File(context.cacheDir, "reports").apply { mkdirs() }
        val safeBeat = beatTitle.replace(Regex("[^A-Za-z0-9]+"), "_")
        val file = File(dir, "${safeBeat}_${from}_${to}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        return file
    }

    // ---- helpers ----

    private fun loadFont(context: Context, asset: String): Typeface? =
        runCatching { Typeface.createFromAsset(context.assets, asset) }.getOrNull()

    private fun paint(color: Int, size: Float, tf: Typeface) = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        this.color = color; textSize = size; typeface = tf
    }

    private fun fill(color: Int) = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        this.color = color; style = Paint.Style.FILL
    }

    private fun stroke(color: Int, w: Float) = Paint(Paint.ANTI_ALIAS_FLAG).apply {
        this.color = color; style = Paint.Style.STROKE; strokeWidth = w
    }

    private fun wrap(text: String, paint: Paint, maxWidth: Float): List<String> {
        if (text.isBlank()) return listOf("")
        val out = ArrayList<String>()
        var line = StringBuilder()
        for (word in text.split(" ")) {
            val candidate = if (line.isEmpty()) word else "$line $word"
            if (paint.measureText(candidate) <= maxWidth) {
                line = StringBuilder(candidate)
            } else {
                if (line.isNotEmpty()) { out.add(line.toString()); line = StringBuilder() }
                if (paint.measureText(word) > maxWidth) {
                    var chunk = StringBuilder()
                    for (ch in word) {
                        if (paint.measureText(chunk.toString() + ch) > maxWidth && chunk.isNotEmpty()) {
                            out.add(chunk.toString()); chunk = StringBuilder()
                        }
                        chunk.append(ch)
                    }
                    line = chunk
                } else line = StringBuilder(word)
            }
        }
        if (line.isNotEmpty()) out.add(line.toString())
        return if (out.isEmpty()) listOf("") else out
    }

    private fun ellipsize(text: String, paint: Paint, maxWidth: Float): String {
        if (paint.measureText(text) <= maxWidth) return text
        var t = text
        while (t.isNotEmpty() && paint.measureText("$t…") > maxWidth) t = t.dropLast(1)
        return "$t…"
    }

    fun open(context: Context, file: File) = launch(context, file, Intent.ACTION_VIEW)
    fun share(context: Context, file: File) = launch(context, file, Intent.ACTION_SEND)

    private fun launch(context: Context, file: File, action: String) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(action).apply {
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_ACTIVITY_NEW_TASK)
            if (action == Intent.ACTION_SEND) {
                type = "application/pdf"
                putExtra(Intent.EXTRA_STREAM, uri)
            } else {
                setDataAndType(uri, "application/pdf")
            }
        }
        val title = if (action == Intent.ACTION_SEND) "Share report" else "Open report"
        runCatching {
            context.startActivity(Intent.createChooser(intent, title).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
        }
    }
}
